services:
    frontend:
        extends:
            file: common.yaml
            service: frontend
        environment:
            NODE_ENV: development
        # depends_on:
        #     api:
        #         condition: service_healthy
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -d "node_modules" ]
                then
                    yarn install
                fi
                yarn run dev

    api:
        extends:
            file: common.yaml
            service: api
        depends_on:
            db:
                condition: service_healthy
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/tasks?page=1&limit=1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -d "node_modules" ]
                then
                    npm install
                fi
                npm run dev

    db:
        image: postgres:15
        env_file:
            - .env
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            TZ: Asia/Kuala_Lumpur
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
            - db-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-volume: