services:
    frontend:
        extends:
            file: common.yaml
            service: frontend
        environment:
            NODE_ENV: development
        # depends_on:
        #     api:
        #         condition: service_healthy
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -d "node_modules" ]
                then
                    yarn install
                fi
                yarn run dev

    api:
        extends:
            file: common.yaml
            service: api
        depends_on:
            db:
                condition: service_healthy
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/tasks?page=1&limit=1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -d "node_modules" ]
                then
                    yarn install
                fi
                yarn run dev

    db:
        image: mysql:8.0
        env_file:
            - .env
        environment:
            TZ: Asia/Kuala_Lumpur
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - db-volume:/var/lib/mysql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-volume: